### ISSUE TITLE
Выбор цвета

### ISSUE THREAD

**Issue by tereshhhchenko** [pitercss/a11y_style#1]
Меняя цвет в ассетах, протестировала его на контрастность, выбрала близкий оттенок оранжевого, который выдает относительно приличную контрастность. Затем вспомнила, что обсуждали еще желтый, и появился второй вариант.

Предлагаю сравнить и выбрать. Новые идеи — тоже велком.

<img src="https://user-images.githubusercontent.com/11773029/62003090-e5403580-b119-11e9-9801-8acc5806a744.png" alt="open" width="150" height="150">
<img src="https://user-images.githubusercontent.com/11773029/62003132-d8701180-b11a-11e9-901c-1197322296eb.png" alt="announcement" width="500">

Цвет: #D23B16
Акцент: #00FA9A
Цвет текста: #ffffff

[Контрастность](https://webaim.org/resources/contrastchecker/): 

4.79:1
**Normal Text**
WCAG AA: Pass ✅
WCAG AAA: Fail ❌
**Large Text**
WCAG AA: Pass ✅
WCAG AAA: Pass ✅
**Graphical Objects and User Interface Components**
WCAG AA:  Pass ✅

[Цветовосприятие](https://www.color-blindness.com/coblis-color-blindness-simulator/)

Цвет сложно идентифицировать, как оранжевый во всех режимах, особенно:
Red-Weak/Protanomaly
Green-Weak/Deuteranomaly
Red-Weak/Protanomaly
Red-Blind/Protanopia
Green-Blind/Deuteranopia
Blue-Blind/Tritanopia
Monochromacy/Achromatopsia

<img src="https://user-images.githubusercontent.com/11773029/62003150-28e76f00-b11b-11e9-9fe5-11adbfbd1eca.png" alt="open" width="150" height="150">
<img src="https://user-images.githubusercontent.com/11773029/62003152-4583a700-b11b-11e9-9168-1fc50681016e.png" alt="announcement" width="500">

Цвет: #494949
Акцент: #F7D419
Цвет текста: #ffffff

[Контрастность](https://webaim.org/resources/contrastchecker/): 

9:1
**Normal Text**
WCAG AA: Pass ✅
WCAG AAA: Pass ✅
**Large Text**
WCAG AA: Pass ✅
WCAG AAA: Pass ✅
**Graphical Objects and User Interface Components**
WCAG AA:  Pass ✅

[Цветовосприятие](https://www.color-blindness.com/coblis-color-blindness-simulator/)

Цвет сложно идентифицировать, как желтый в режимах:
Blue-Blind/Tritanopia
Monochromacy/Achromatopsia

**Comment by tereshhhchenko** [comment]
Есть еще вариант с желтым фоном:
<img src="https://user-images.githubusercontent.com/11773029/62003338-6c8fa800-b11e-11e9-97dc-352f5edd87fb.png" alt="open" width="150" height="150">
<img src="https://user-images.githubusercontent.com/11773029/62003308-01de6c80-b11e-11e9-8c55-f046a1329bd4.png" alt="announcement" width="500">

[Контрастность](https://webaim.org/resources/contrastchecker/): 

13.96:1
**Normal Text**
WCAG AA: Pass ✅
WCAG AAA: Pass ✅
**Large Text**
WCAG AA: Pass ✅
WCAG AAA: Pass ✅
**Graphical Objects and User Interface Components**
WCAG AA:  Pass ✅

[Цветовосприятие](https://www.color-blindness.com/coblis-color-blindness-simulator/)

Цвет сложно идентифицировать, как оранжевый во всех режимах, особенно:
Blue-Blind/Tritanopia
Monochromacy/Achromatopsia

**Comment by TatianaFokina** [comment]
Мне нравятся все варианты. В первом только не нравится цвет звёздочки, хотя он и комплиментарный. Можно попробовать #008559.
Второй минималистичный, что хорошо, но скучноватый.
**Третий понравился больше всех**. Он интереснее и ярче, в плане читаемости текста всё хорошо. Единственный его минус — это фиолетовая звёздочка, которая сливается с тёмный фоном на фотографии спикера. Но, возможно, это не такая уж большая проблема. Так что я голосую за жёлтый.

**Comment by vasiliy-dudin** [comment]
Да, в первом варианте астериск слегка вырвиглазный. 3 хороший и свежий, но нижний астериск может часто сливаться с фотографией. 

Можно так: https://kutt.it/ViBRKf 
Цвет #ab0976, AAA проходит.

**Comment by pepelsbey** [comment]
Мне жёлтый с самого начала нравился больше оранжевого :) Так что последнее предложение Василия кажется самым хорошим.

**Comment by TatianaFokina** [comment]
С такой звёздочкой совсем хорошо.

**Comment by tereshhhchenko** [comment]
Желтый it is!
